#!/bin/sh

. /etc/rc.conf

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

# Configure host name
if [ "$HOSTNAME" ]; then
  echo "hostname: $HOSTNAME"
  /bin/hostname $HOSTNAME
fi

while true; do
  setsid cttyhack /bin/sh &
  wait
done
